```{r}
# Packages
library(tidyverse)
library(ggplot2)
library(gsignal)
library(forcats)
library(htmltools)
```

```{r eval = FALSE}
library(rlist)
list <- tagList()
for(i in c(1,2,3,4,5,6)){
  list <- list.append(list, div(
    p(1),
    p(9)
  ))
}
list
length(list)

LIST <- tagList(div(p(1),p(2)),
        div(p(1),p(2)),
        div(p(1),p(2)),
        div(p(1),p(2)),
        div(p(1),p(2)),
        div(p(1),p(2)))
length(LIST)
```

```{r}
# Importing Cleaned Datasets
labelled_movies <- c("Buddy","Hobbit","Machete","Mitty","Paranormal","Hunger")
#for(i in labelled_movies){assign(i,read_csv(sprintf("./src/data/cleaned/%s_cleaned.csv",i)))}

# Importing Snipped Datasets
for(i in c("ms_data","screen_times","label_set")){
  assign(i,read_csv(sprintf("./src/data/cleaned/snipped_%s.csv",i)))
}

fear_labels <- grep("death|suspense|horror|murder|aggressive|violence|shock", 
                    label_set$label, 
                    value=TRUE)
ms_data %>% dplyr::filter(movie == "Paranormal Activity: The Marked Ones") %>% distinct(label)

fear_cmpd_ranked <-
    ms_data %>% 
      dplyr::filter(!is.na(label)) %>%
      mutate(is.fear = if_else(grepl(paste(fear_labels, collapse="|"),label),"Fear","Others")) %>%
      group_by(is.fear)%>%
      reframe(across(matches("^\\d"), sum)) %>%
      reframe(across(matches("^\\d"),function(x){x/sum(x)})) %>%
      mutate(is.fear=c("Fear","Others")[row_number(`14.0028`)]) %>%
      pivot_longer(
        cols = matches("^\\d"),
        names_to = "cmpd",
        values_to = "fraction"
      ) %>% 
      dplyr::filter(is.fear == "Fear") %>%
      arrange(desc(fraction))
ms_data %>% 
      dplyr::filter(!is.na(label)) %>%
      mutate(is.fear = if_else(grepl(paste(fear_labels, collapse="|"),label),"Fear","Others")) %>%
      group_by(is.fear)%>%
      reframe(across(matches("^\\d"), sum)) %>%
      reframe(across(matches("^\\d"),function(x){x/sum(x)})) %>%
      mutate(is.fear=c("Fear","Others")[row_number(`14.0028`)]) %>%
      pivot_longer(
        cols = matches("^\\d"),
        names_to = "cmpd",
        values_to = "fraction"
      ) %>% 
      dplyr::filter(is.fear == "Fear") %>%
      arrange(desc(fraction)) %>%
      mutate(fraction=fct_inorder(fraction,levels=fr))


ms_data %>% 
    dplyr::filter(!is.na(label)) %>%
    pivot_longer(
      cols = matches("^\\d"),
      names_to = "cmpd",
      values_to = "conc"
    ) %>% 
    {if(Y) dplyr::filter(., conc > 1) else(.)} %>%
    distinct(cmpd) %>%
    '[['("cmpd") %>%
      factor(levels = fear_cmpd_ranked$cmpd, ordered=TRUE) %>%
  sort()
fear_cmpd_ranked$cmpd
Y <- TRUE  

fear_cmpd_ranked <-
    ms_data %>% 
      dplyr::filter(!is.na(label)) %>%
      mutate(is.fear = if_else(grepl(paste(fear_labels, collapse="|"),label),"Fear","Others")) %>%
      group_by(is.fear)%>%
      reframe(across(matches("^\\d"), sum)) %>%
      reframe(across(matches("^\\d"),function(x){x/sum(x)})) %>%
      mutate(is.fear=c("Fear","Others")[row_number(`14.0028`)]) %>%
      pivot_longer(
        cols = matches("^\\d"),
        names_to = "cmpd",
        values_to = "fraction"
      ) %>% 
      dplyr::filter(is.fear == "Fear") %>%
      arrange(desc(fraction))

# Labelled ms_data (Only 6 diff movies)
labelled_ms <- ms_data %>% 
  dplyr::filter(!is.na(label))

labelled_ms


exp_labelled_ms <- labelled_ms %>% #To separate labels
  separate_longer_delim(
    cols = label,
    delim = "; "
  ) 



tidied_labelled_ms <- exp_labelled_ms %>% #To categorise fear and non-fear labels
  mutate(is.fear = if_else(label %in% fear_labels, "Fear","Others")) #(TODO: SHINY SELECT WHAT's FEAR)

# Unlabelled ms_data (Excluding the buffer time before labelled movies start)
unlabelled_ms <- ms_data %>% 
  dplyr::filter(is.na(label))
```

```{r}
# Graph 1
# A segmented bar plot of compound concentrations against compound mass labels. Bar plots will be segmented by total % concentration under each fear label. This will allow us to observe which compounds are most commonly present when in fear. Based on the observations, a narrowed list of compounds will be analysed in the later graphs (List A)

#Chosen Colour Palette (TODO)
colour_palette <- c("#a9a9f9","#009699","red","orange","yellow","green")
colour_gradient <- c("#009699","royalblue","#a9a9f9") #Low to high conc
colour_bkg <- c("#a9a9f9","#009699") #contrasting w each other and w palette

#Scenes were double-counted if fell under both fear and non-fear scene labels

graph_1 <- tidied_labelled_ms %>% #To introduce %
  group_by(cmpd) %>%
  mutate(Tconc = sum(conc)) %>%
  group_by(cmpd,is.fear) %>%
  mutate(fraction = sum(conc)/Tconc) %>%
  distinct(cmpd,is.fear,fraction) %>%
  arrange(is.fear, desc(fraction))

#For later stuff
fear_cmpd_ranked <- graph_1$cmpd[1:(length(graph_1$cmpd)/2)]

#For user input in shiny (TODO) 
user_start_rank_1 <- 1
user_end_rank_1 <- 25

select_to_plot_1 <- graph_1[c(user_start_rank_1:user_end_rank_1, (length(graph_1$cmpd)-user_start_rank_1+1):(length(graph_1$cmpd)-user_end_rank_1+1)),]

fear_cmpd_ranked %>%
  slice(user_start_rank_1:user_end_rank_1) %>%
  ggplot(aes(y = fct_reorder(cmpd,fraction), x = fraction)) +
  geom_col(fill = colour_palette[1]) + 
  labs(title = paste("Top",user_start_rank_1,"to",user_end_rank_1,"Most Frequently Emitted Compounds when in Fear"),
       subtitle = "Identified by distribution across different types of scenes",
       y = "m/z of Compound", 
       x = "Fraction of the Total Concentration") +
  theme(panel.background = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_text(margin = margin(r = 10)),
        axis.title.x = element_text(margin = margin(t = 10)),
        plot.subtitle = element_text(margin = margin(b = 10))
        ) + 
  scale_x_continuous(expand = c(0, 0))

ms_data %>% 
      dplyr::filter(!is.na(label)) %>%
      select(label) %>%
      separate_longer_delim(
        cols = label,
        delim = "; "
      ) %>%
      ggplot(aes(y=label)) +
      geom_bar(fill = colour_palette[1]) +
      labs(title = paste("Distribution of scenes"),
           y = "Type of Scene", 
           x = "Count") + 
      theme(axis.line = element_line(linewidth = 0.3, arrow = arrow(type='closed', length = unit(5,'pt'))),
            panel.background = element_blank())



%>%
  select_if(where(~(all(.x<0.5))))
  
  
ms_data %>%
    pivot_longer(
      cols = matches("^\\d"),
      names_to = "cmpd",
      values_to = "conc"
    ) %>% 
    {if(Y) dplyr::filter(., conc > 0.5) else(.)} %>%
    separate_longer_delim(
      cols = label,
      delim = "; "
    ) %>% 
    {if(Y) dplyr::filter(., label != "conversation: general", label != "conversation: conversation main actor") else(.)} %>% 
    distinct(cmpd) %>%
    '[['("cmpd") %>%
      factor(levels = fear_cmpd_ranked$cmpd, ordered=TRUE) %>%
      sort()

#NEW
ms_data %>% 
  dplyr::filter(!is.na(label)) %>%
  {if(Y) dplyr::filter(.,grepl(paste(label_set$label[!label_set$label %in% c("conversation: general", "conversation: conversation main actor")], collapse="|"),label)) else(.)} %>%
  select(matches("^\\d")) %>% 
  select_if(., where(~any(.x>0.5))) %>%
  colnames() %>%
  factor(levels = fear_cmpd_ranked$cmpd, ordered=TRUE) %>%
  sort()

#scale_fill_manual(values=c("red","blue")
#scale_x_discrete(guide=guide_axis(angle=90))
#scale_fill_brewer(palette="Set3")

select_to_plot_1 <- graph_1[c(user_start_rank_1:user_end_rank_1, (length(graph_1$cmpd)-user_start_rank_1+1):(length(graph_1$cmpd)-user_end_rank_1+1)),]
  
    select_to_plot_1 %>%
      group_by(is.fear) %>%
      mutate(cmpd = fct_reorder(as.character(cmpd), fraction)) %>%
      ggplot(aes(y = cmpd, x = fraction)) +
      geom_col() + 
      labs(title = paste("Top",user_start_rank_1,"to",user_end_rank_1,"Most Frequently Emitted Compounds when in Fear"),
           subtitle = "Identified by distribution across different types of scenes",
           y = "m/z of Compound", 
           x = "Fraction of the Total Concentration", 
           fill = "Type of Scene") + 
      scale_fill_manual(values=colour_palette) +
      theme(panel.background = element_blank(),
            axis.ticks.y = element_blank(),
            axis.title.y = element_text(margin = margin(r = 10)),
            axis.title.x = element_text(margin = margin(t = 10)),
            plot.subtitle = element_text(margin = margin(b = 10))
      ) + 
      scale_x_continuous(expand = c(0, 0))
    
    ms_data %>% 
    dplyr::filter(!is.na(label), grepl(paste(
label_set$label[!label_set$label %in% c("conversation: general")], collapse="|"),label)) %>%
  select_if(where(~all(.x<0.5)))
```

```{r}
# Graph 2 (Changed from bar to hex)
# A bar graph displaying the total concentration of a specific chosen compound under each scene label. This will give a clearer idea of the distribution of the selected compound across different types of scenes. This will only be for compounds in List A.

#DOUBLE-COUNTING

#MORE SHINY TASKS: Add info about bin when hover over hex (TODO)

#For user input in Shiny (TODO)
user_cmpd_2 <- "60.0490"
user_cmpd_2 <- "235.1928"
user_cmpd_2 <- "48.0205"

Y <- TRUE
ms_data %>% 
  dplyr::filter(!is.na(label)) %>%
  select(`user_cmpd_2`,movie_F_ind, label) %>%
  pivot_longer(
    cols = matches("^\\d"),
    names_to = "cmpd",
    values_to = "conc"
  ) %>% 
  { if(Y) dplyr::filter(.,conc>0) else(.)} %>%
  mutate(conc_perpax = conc/screen_times$number.visitors[movie_F_ind]) %>%
  select(-conc, -movie_F_ind, -cmpd) %>%
  separate_longer_delim(
    cols = label,
    delim = "; "
  )

#with 0 --> Highlights that be at 0 and relatively same amount of time (Due to vagueness of scene labels)
tidied_labelled_ms %>% 
  dplyr::filter(cmpd == user_cmpd_2) %>%
  ggplot(aes(x=conc_perpax, y=label)) + 
  geom_hex() +
  labs(title = paste("Distribution of compound with m/z =",user_cmpd_2,"across different scenes"),
       subtitle = "Inclusive of data points where compound is absent",
       y = "Type of Scene", 
       x = "Concentration per Pax per Scene") + 
  scale_fill_gradientn(colours = colour_gradient)
  
#without 0 points --> For better idea of distribution
ms_data %>% 
  dplyr::filter(!is.na(label)) %>%
  select(`user_cmpd_2`,movie_F_ind, label) %>%
  pivot_longer(
    cols = matches("^\\d"),
    names_to = "cmpd",
    values_to = "conc"
  ) %>% 
  { if(Y) dplyr::filter(.,conc>0) else(.)} %>%
  mutate(conc_perpax = conc/screen_times$number.visitors[movie_F_ind]) %>%
  select(-conc, -movie_F_ind, -cmpd) %>%
  separate_longer_delim(
    cols = label,
    delim = "; "
  ) %>%
  ggplot(aes(x=conc_perpax, y=label)) + 
  geom_hex() + 
  labs(title = paste("Distribution of compound with m/z =",user_cmpd_2,"across different scenes"),
       subtitle = "Excluding data points where compound is absent",
       y = "Type of Scene", 
       x = "Concentration per Pax perScene") + 
  scale_fill_gradientn(colours = colour_gradient)

ms_data %>% 
      dplyr::filter(!is.na(label), movie == "Paranormal Activity: The Marked Ones") %>%
      select(label) %>%
      separate_longer_delim(
        cols = label,
        delim = "; "
      ) %>%
      ggplot(aes(y=label)) +
      geom_bar(fill = colour_palette[1]) +
      labs(title = paste("Distribution of scenes"),
           y = "Type of Scene", 
           x = "Count") + 
      theme(axis.line = element_line(linewidth = 0.3, arrow = arrow(type='closed', length = unit(5,'pt'))),
            panel.background = element_blank())


zeros <- TRUE
if(zeros == TRUE){
  graph_2t <- tidied_labelled_ms %>% dplyr::filter(conc > 0)
} else {
  graph_2t <- tidied_labelled_ms
}
#without 0 points --> For better idea of distribution
graph_2t %>% 
  dplyr::filter(cmpd == user_cmpd_2) %>%
  ggplot(aes(x=conc_perpax, y=label)) + 
  geom_hex() + 
  labs(title = paste("Distribution of compound with m/z =",user_cmpd_2,"across different scenes"),
       subtitle = paste(if_else(zeros == FALSE, "Excludes", "Includes"), "data points where compound is absent"),
       y = "Type of Scene", 
       x = "Concentration per Pax per Scene") + 
  scale_fill_gradientn(colours = colour_gradient)

ms_data %>% 
      dplyr::filter(!is.na(label)) %>%
      select(user_cmpd_2,movie_F_ind, label) %>%
      pivot_longer(
        cols = matches("^\\d"),
        names_to = "cmpd",
        values_to = "conc"
      ) %>% 
      {if(Y) dplyr::filter(.,conc>0) else(.)} %>%
      {if(Y) dplyr::filter(.,conc>1) else(.)}%>%
      mutate(conc_perpax = conc/screen_times$number.visitors[movie_F_ind]) %>%
      select(-conc, -movie_F_ind, -cmpd) %>%
      separate_longer_delim(
        cols = label,
        delim = "; "
      ) %>% 
      {if(Y) dplyr::filter(., label != "conversation: general", label != "conversation: conversation main actor") else(.)} %>% 
      ggplot(aes(x=conc_perpax, y=label)) + 
      geom_hex() +
      labs(title = paste("Distribution of compound with m/z =",user_cmpd_2,"across different scenes"),
           subtitle = paste(if_else(Y, "Excludes", "Includes"), "data points where compound is absent"),
           y = "Type of Scene", 
           x = "Concentration per Pax per Scene") + 
      scale_fill_gradientn(colours = colour_gradient) + 
      theme(axis.line = element_line(linewidth = 0.3, arrow = arrow(type='closed', length = unit(5,'pt'))))
```

```{r}
# Graph 3 #REMOVE? USELESS
# Multiple box plots will be plot to display the distribution of a compound's concentration under different scene labels. This will give a clearer idea of the distribution of concentrations, instead of just the total concentration across all similar scenes.  This will only be for compounds in List A.

```

```{r}
# Graph 4 (OPTIMISED)

# Other Shiny (TODO): Hover over facet for a zoom in (Show plot alone)

#For user input in Shiny (TODO)
user_movie_3 <- "Paranormal Activity: The Marked Ones"
user_top_cmpd_3 <- 1 #A range selected by user
user_bottom_cmpd_3 <- 15
user_count_cmpd_3 <- user_bottom_cmpd_3 - user_top_cmpd_3 + 1

#Vector of selected compounds
selected_cmpd_3 <- fear_cmpd_ranked$cmpd[user_top_cmpd_3:user_bottom_cmpd_3]

graph_3t <- labelled_ms %>% 
  dplyr::filter(movie == user_movie_3) %>%
  mutate(is.fear = if_else(grepl(paste(fear_labels, collapse="|"),label), "Fear","Others"))

graph_3t <- labelled_ms %>% 
  dplyr::filter(movie == user_movie_3) %>%
  mutate(is.fear = if_else(label %in% fear_labels, "Fear","Others")) %>%
  dplyr::filter(cmpd %in% selected_cmpd_3) %>% #Select top cmpd
  group_by(counter,cmpd) %>% #To add an ave conc common to similar movies
  mutate(average = mean(conc_perpax)) %>% 
  group_by(cmpd) %>% 
  mutate(sum = sum(conc)) %>% ungroup()


# Vector of absent cmpd (Complete Absence)
removed_cmpd <- dplyr::filter(distinct(graph_3t, cmpd, sum), sum == 0)$cmpd

graph_3 <- graph_3t %>% 
  dplyr::filter(sum != 0) %>% 
  distinct(counter,cmpd, .keep_all = TRUE) %>% #To remove movie duplicates
  transform(cmpd=factor(cmpd, levels=selected_cmpd_3)) %>%
  arrange(cmpd, desc(is.fear))
  
removed_cmpd <- ms_data %>% 
  dplyr::filter(movie == user_movie_3) %>%
  select(all_of(selected_cmpd_3)) %>%
  select_if(~all(.==0)) %>%
  colnames()

removed_cmpd
selected_cmpd_3
if_else(length(removed_cmpd) == length(selected_cmpd_3), 0,1)

# Plot
ms <- 9
if(ms != 0){
  ms_data %>% 
    dplyr::filter(!is.na(label)) %>%
    dplyr::filter(movie == user_movie_3) %>%
    select(all_of(selected_cmpd_3[!selected_cmpd_3 %in% removed_cmpd]),counter,label) %>%
    group_by(counter,label) %>%
    reframe(across(matches("^\\d"), mean)) %>%
    mutate(is.fear = if_else(grepl(paste(fear_labels, collapse="|"),label), "Fear","Others")) %>%
    pivot_longer(
      cols = matches("^\\d"),
      names_to = "cmpd",
      values_to = "average"
    )  %>% #To remove movie duplicates
    transform(cmpd=factor(cmpd, levels=selected_cmpd_3)) %>%
    arrange(cmpd, desc(is.fear)) %>% #NOTE: IF PLOT CONC, A FEW COMPLETE ABSENCE
    ggplot(aes(x=counter/2, y=average, colour=fct_inorder(is.fear))) + 
    geom_point(alpha=0.7) + 
    facet_wrap(~ cmpd, 
               ncol = ceiling(sqrt(user_count_cmpd_3-length(removed_cmpd))), 
               scales="free", 
               labeller = as_labeller(~ paste0("No. ", user_top_cmpd_3 + which(selected_cmpd_3 %in% .x) - 1,":\n", .x))) +
    guides(color = guide_legend(reverse=TRUE))+
    labs(title = paste("Distribution of Top", 
                       user_top_cmpd_3, 
                       "to", 
                       user_bottom_cmpd_3, 
                       "Fear Compounds in", 
                       user_movie_3),
         subtitle = "Concentrations are averaged",
         y = "Concentration per Scene", 
         x = "Duration of Movie",
         caption = str_wrap(if_else(length(removed_cmpd) != 0, 
                           paste(if_else(length(removed_cmpd)>1, "Plots", "Plot"),
                                 "for",
                                 if_else(length(removed_cmpd)>1, "compounds", "compound"),
                                 "with m/z =",
                                 paste(removed_cmpd, collapse=", "), 
                                 if_else(length(removed_cmpd)>1, "have", "has"),
                                 "been removed due to absence throughout movie."),
                           NA), 150),
         color = "Type of Scene"
         ) + 
    theme(axis.text.y = element_text(size=5),
          axis.text.x = element_text(size=5),
          strip.text = element_text(size=6, margin=margin(t=1,b=2)),
          strip.background.x = element_rect(fill=colour_palette),
          panel.spacing = unit(1, "lines"),
          panel.background = element_blank(),
          panel.border = element_rect(fill = NA, linewidth = 0.1, color = "grey"),
          plot.caption = element_text(hjust=0)) +
    scale_color_manual(values = colour_palette)
} else{
  print("All compounds selected were absent throughout the movie selected.")
}
```

```{r}
# Graph 4 (now 3) *Prioritised Fear labels
# A line graph for the concentration of a chosen compound against time. The time will reflect the duration into a movie. Meanwhile, the list of compounds is once again restricted to List A. Multiple graphs will be either faceted or overlaid to observe the trend for the different compounds in the same movie. Scenes/Points with fear labels will be highlighted.

# Other Shiny (TODO): Hover over facet for a zoom in (Show plot alone)

#For user input in Shiny (TODO)
user_movie_3 <- "Paranormal Activity: The Marked Ones"
user_top_cmpd_3 <- 1 #A range selected by user
user_bottom_cmpd_3 <- 15
user_count_cmpd_3 <- user_bottom_cmpd_3 - user_top_cmpd_3 + 1

#Vector of selected compounds
selected_cmpd_3 <- fear_cmpd_ranked[user_top_cmpd_3:user_bottom_cmpd_3]

graph_3 <- tidied_labelled_ms %>% arrange(is.fear) %>%
  distinct(Time, cmpd, .keep_all = TRUE) %>% #To remove expanded labels
  arrange(counter, cmpd) %>% 
  dplyr::filter(cmpd %in% selected_cmpd_3) %>% #Select top cmpd
  dplyr::filter(movie==user_movie_3)  %>% #Select 1 movie
  group_by(counter,cmpd) %>% #To add an ave conc common to similar movies
  mutate(average = mean(conc_perpax)) %>% ungroup()

# Set a list of cmpd to remove (Complete Absence)
removed_cmpd <- graph_3 %>% pivot_wider(
  names_from = "cmpd",
  values_from = "conc",
  id_cols="Time"
) %>% select_if(function(x){all(x==0) & is.numeric(x)}) %>% colnames()

if(length(removed_cmpd) != 0){
  graph_3 <- graph_3 %>% 
    dplyr::filter(!cmpd %in% removed_cmpd)
}

final_graph_3 <- graph_3 %>% 
    transform(cmpd=factor(cmpd, levels=selected_cmpd_3)) %>%
    arrange(cmpd) %>% #To look at only 1 movie duration
    distinct(counter, cmpd, .keep_all = TRUE) 

# Plot
if(length(final_graph_3$cmpd) != 0){
  final_graph_3 %>% #NOTE: IF PLOT CONC, A FEW COMPLETE ABSENCE
    ggplot(aes(x=counter/2, y=average, colour=is.fear)) + 
    geom_point(alpha=0.7) + 
    facet_wrap(~ cmpd, 
               ncol = ceiling(sqrt(user_count_cmpd_3-length(removed_cmpd))), 
               scales="free", 
               labeller = as_labeller(~ paste0("No. ", user_top_cmpd_3 + which(selected_cmpd_3 %in% .x) - 1,":\n", .x))) + 
    labs(title = paste("Distribution of Top", 
                       user_top_cmpd_3, 
                       "to", 
                       user_bottom_cmpd_3, 
                       "Fear Compounds in", 
                       user_movie_3),
         subtitle = "Concentrations are averaged",
         y = "Concentration per Scene", 
         x = "Duration of Movie",
         caption = str_wrap(if_else(length(removed_cmpd) != 0, 
                           paste(if_else(length(removed_cmpd)>1, "Plots", "Plot"),
                                 "for",
                                 if_else(length(removed_cmpd)>1, "compounds", "compound"),
                                 "with m/z =",
                                 paste(removed_cmpd, collapse=", "), 
                                 if_else(length(removed_cmpd)>1, "have", "has"),
                                 "been removed due to absence throughout movie."),
                           NA), 150),
         color = "Type of Scene"
         ) + 
    theme(axis.text.y = element_text(size=5),
          axis.text.x = element_text(size=5),
          strip.text = element_text(size=6, margin=margin(t=1,b=2)),
          strip.background.x = element_rect(fill=colour_palette),
          panel.spacing = unit(1, "lines"),
          panel.background = element_blank(),
          panel.border = element_rect(fill = NA, linewidth = 0.1, color = "grey"),
          plot.caption = element_text(hjust=0)) +
    scale_color_manual(values = colour_palette)
} else{
  print("All compounds selected were absent throughout the movie selected.")
}
```

```{r}
# Graph 5 (now 4)
# For a chosen compound, different screenings of the same movie are selected and the concentration of that compound against time is plot and overlaid for the different screenings. These screenings will be selected according to a criteria set by the user, such that the other variables for those screenings are relatively similar. This allows us to observe for any trends between the compound emission and factors such as the time of day, type of fear, and the influence of people.

# Hover for zoom in of that specific screening plot (TODO)
# Selection of screenings to focus on (TODO)
# https://stackoverflow.com/questions/42259826/hyperlinking-text-in-a-ggplot2-visualization (CONSIDER)

#For user input in Shiny (TODO)
user_movie_4 <- "Paranormal Activity: The Marked Ones"
user_cmpd_4 <- "19.0096" #A range selected by user

removed_screens <- ms_data %>% 
  dplyr::filter(movie == user_movie_4) %>%
  select(user_cmpd_4,movie_F_ind,counter) %>%
  group_by(movie_F_ind) %>%
  pivot_wider(
    names_from = movie_F_ind,
    values_from = user_cmpd_4,
    id_cols = counter
  ) %>%
  select_if(~all(.==0)) %>%
  colnames()

dplyr::filter(!is.na(label)) %>%
    group_by(counter,label) %>%
    reframe(across(matches("^\\d"), mean)) %>%
    mutate(is.fear = if_else(grepl(paste(fear_labels, collapse="|"),label), "Fear","Others")) %>%
    pivot_longer(
      cols = matches("^\\d"),
      names_to = "cmpd",
      values_to = "average"
    )  %>% #To remove movie duplicates
    transform(cmpd=factor(cmpd, levels=selected_cmpd_3)) %>%
    arrange(cmpd, desc(is.fear)) %>% #NOTE: IF PLOT CONC, A FEW COMPLETE ABSENCE
  
graph_4 <- tidied_labelled_ms %>% arrange(is.fear) %>%
  distinct(Time, cmpd, .keep_all = TRUE) %>% #To remove expanded labels
  arrange(counter, cmpd) %>% 
  dplyr::filter(cmpd == user_cmpd_4) %>% #Select top cmpd
  dplyr::filter(movie==user_movie_4) %>% #Select 1 movie
  mutate(movie_F_ind = fct_reorder2(as.character(movie_F_ind), counter, conc_perpax)) %>% arrange(movie_F_ind) 

# FOR SCREENING SELECTION (TODO)
# %>% dplyr::filter(movie_F_ind %in% c(99,100))
  
#TODO: Uncheck screenings that are in removed_screens

graph_4_info <- ms_data %>% 
  dplyr::filter(!is.na(label),
                movie == user_movie_4,
                movie_F_ind %in% selected_screenings) %>%
  select(user_cmpd_4,counter,label,movie_F_ind) %>%
  group_by(movie_F_ind) %>%
  pivot_longer(
      cols = matches("^\\d"),
      names_to = "cmpd",
      values_to = "conc"
    ) %>%
  ungroup() %>%
  mutate(conc_perpax = (max(conc/screen_times$number.visitors[movie_F_ind])-min(conc/screen_times$number.visitors[movie_F_ind]))) %>%
  distinct(counter,.keep_all = TRUE) %>%
  mutate(is.fear = if_else(grepl(paste(fear_labels, collapse="|"),label),"Fear","Others")) %>%
  select(counter, is.fear,conc_perpax)

graph_4_height_info <- 
  dplyr::filter(ms_data,!is.na(label),
                movie == user_movie_4,
                movie_F_ind %in% selected_screenings) %>%
  pivot_longer(
      cols = matches("^\\d"),
      names_to = "cmpd",
      values_to = "conc"
    ) %>%
  ungroup() %>%
  mutate(conc_perpax = conc/screen_times$number.visitors[movie_F_ind]) %>% 
  '[['(`user_cmpd_4`)


selected_screenings <- c(99,100)
ms_data %>% 
  dplyr::filter(!is.na(label),
                movie == user_movie_4) %>%
  {if(length(selected_screenings != 0)) {if(.$movie[1] %in% screen_times$movie[selected_screenings]) dplyr::filter(., movie_F_ind %in% selected_screenings) else(.)} else(.)} %>% distinct(movie_F_ind)

%>%
  select(user_cmpd_4,counter,label,movie_F_ind) %>%
  pivot_longer(
      cols = matches("^\\d"),
      names_to = "cmpd",
      values_to = "conc"
    ) %>%
  mutate(conc_perpax = conc/screen_times$number.visitors[movie_F_ind]) %>%
  mutate(movie_F_ind = fct_reorder2(as.character(movie_F_ind), counter, conc_perpax)) %>%
  arrange(movie_F_ind) %>% #NOTE: IF PLOT CONC, A FEW COMPLETE ABSENCE
  ggplot(aes(x=counter/2, y=conc_perpax)) + 
  geom_tile(data = graph_4_info %>% dplyr::filter(is.fear == "Fear"),
            height=max(graph_4_height_info)-min(graph_4_height_info),
            aes(fill="Fear"),linetype=0,alpha=0.3) +
  geom_tile(data = graph_4_info %>% dplyr::filter(is.fear == "Others"), 
            height=max(graph_4_height_info)-min(graph_4_height_info), 
            aes(fill="Others"),linetype=0,alpha=0.1) +
  geom_line(aes(group = movie_F_ind, color = movie_F_ind)) +
  labs(title = paste("Distribution of compound with m/z =", 
                     user_cmpd_4, 
                     "across duration of", 
                     user_movie_4),
       subtitle = "Each screening is represented by a line graph.",
       y = "Concentration per Scene", 
       x = "Duration of Movie (min)",
       color = "Screening",
       fill = "Type of Scene") + 
  theme(panel.background = element_blank()) + 
  scale_fill_manual(values = colour_bkg) +
  scale_color_manual(values = colour_palette) +
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0))
screen_times$movie[movie]
# Print Screening Details (By clicking on label) (TODO)
graph_4 %>% distinct(movie_F_ind) %>% arrange(movie_F_ind)
# movie A 
graph_4 %>% distinct(movie_F_ind) %>% arrange(movie_F_ind) # %>% ...
# No. of people, Time of day, Date (Maybe got spoilers so less scared haha)
```

```{r}
# Graph 6 (now 5)
# For the top fear compounds determined, their average emission will be tabulated for different movies, throughout the movie and across multiple screenings. This emission intensity will be plot against the online fear ratings for these movies to give an idea of whether the online ratings are an accurate reflection of our chemical reflection, vice versa.

#TODO: Update!
Final_fear_cmpd_ranked <- fear_cmpd_ranked

#Fear Type A: Identified w cmpd A
user_cmpd_5 <- "235.1928" #SELECT from really narrowed few (TODO)

ms_data %>% 
  dplyr::filter(!is.na(label)) %>%
  select(user_cmpd_5,counter,label,movie,movie_F_ind) %>%
  pivot_longer(
      cols = matches("^\\d"),
      names_to = "cmpd",
      values_to = "conc"
    ) %>%
  mutate(conc_perpax = conc/screen_times$number.visitors[movie_F_ind]) %>% 
  ggplot(aes(x = conc_perpax, y = movie)) +
  geom_boxplot() +
  labs(x = "Concentration per Pax per Scene", 
       y = "Movie",
       title = paste("Distribution of compound with m/z =", user_cmpd_5))

ms_data %>%
  select(user_cmpd_5,counter,label,movie,movie_F_ind) %>%
  pivot_longer(
      cols = matches("^\\d"),
      names_to = "cmpd",
      values_to = "conc"
    ) %>%
  group_by(movie) %>%
  mutate(conc_perpax = conc/screen_times$number.visitors[movie_F_ind],
         overall_ave_conc_perpax = mean(conc_perpax)) %>%
  ungroup() %>%
  distinct(movie, .keep_all = TRUE) %>%
  mutate(fear_rating = screen_times$fear_rating[movie_F_ind]) %>% 
  ggplot(aes(x = fear_rating, y = overall_ave_conc_perpax)) +
  geom_point() + geom_line() + 
  labs(x = "Online Fear Ratings",
       y = "Average Concentration per Pax per Scene",
       title = "Comparison of Actual and Expected Fear Ratings", 
       subtitle = paste("Based on compound with m/z =",user_cmpd_5), 
       #caption = "Fear ratings are an average of rating obtained from Reel Scary and Common Sense Media",
       caption=a("ggplot2 Package", href = "https://ggplot2.tidyverse.org/"))




#DONT EXACTLY UNDERSTAND, but it gets the hyperlink (TODO SUSSSS)
library(grid)
## Force 'grid' grobs from 'ggplot2' plot
grid.force()
## List all grobs in plot
grid.ls()
## Find the grobs representing the text labels on the axes
tickLabels <- grid.grep("caption::text", grep=TRUE, global=TRUE)
## Check which one is the y-axis
lapply(tickLabels, function(x) grid.get(x)$label)


## Add hyperlinks to the axis tick labels
library(gridSVG)
grid.hyperlink(tickLabels[[1]],
               href="https://ggplot2.tidyverse.org/",
               group=FALSE)
## Export to SVG (and view in a browser)
grid.export("linked-plot.svg")



#without 0 values ?(TBC)
graph_5c <- graph_5a %>%
  dplyr::filter(conc>0)

graph_5c %>% 
  ggplot(aes(x = conc_perpax, y = movie)) +
  geom_boxplot() +
  labs(x = "Concentration per Pax per Scene", 
       y = "Movie",
       title = paste("Distribution of compound with m/z =", user_cmpd_5))
```

# Old Graphs/Code
```{r eval=FALSE}
#Graph 2 average values --> Did not work out since lots of 0
graph_2 <- tidied_labelled_ms %>% #To ave conc per scene
  dplyr::filter(cmpd == user_cmpd_2) %>%
  group_by(label) %>%
  mutate(average = mean(conc)) %>%
  distinct(label,average, cmpd) %>%
  arrange(desc(average))
  
graph_2 %>%
  ggplot(aes(y = average, x = label)) +
  geom_col() + 
  labs(title = paste("Distribution of Compound of m/z =",user_cmpd_2,"across different scene labels"),
       subtitle = "For scenes with more than 1 label assigned, concentrations were double-counted",
       y = "Average Concentration per Scene", 
       x = "Type of Scene") + 
  scale_x_discrete(guide=guide_axis(angle=90))
```